### ISSUE TITLE
percent_packets_lost_out should range from 0 to 100

### ISSUE THREAD

**Issue by rodrigodc** [oanguenot/webrtc-stats#5]
Hello,

First of all, thanks for this excellent library.

## Suggestion

Adjust `percent_packets_lost_out` to range from `0` to `100`, for the sake of symmetry with `percent_packets_lost_in`.

## Reason

- It currently ranges from `0` to `1`, meaning a fraction (_at least in Google Chrome_, which I have tested).
- On the other hand, its counterpart `percent_packets_lost_in` ranges from `0` to `100`, meaning an absolute percentage number.

## Moreover

- Both `mos_out` and `mos_emodel_out` are currently innacurate due to that `[0,1]` range.
- With the adjustment, they become accurate (just like `mos_in` and `mos_emodel_in` are).

## Proposal

It seems that just multiplying `fractionLost` by `100` in `extractor.js` would do the job:

```diff
-    fractionLost = Number(bunch[PROPERTY.FRACTION_LOST]);
+    fractionLost = Number(100 * bunch[PROPERTY.FRACTION_LOST]);
```

I have tested that change myself and it seems to work.

I am available to send a PR with it if you agree, just let me know.

Thank you,
Rodrigo

**Comment by oanguenot** [comment]
Hi @rodrigodc, thanks for the report and the correction.
Yes, for sure, you can submit your PR.
Thanks in advance

**Comment by rodrigodc** [comment]
Hi @oanguenot,

PR #6 submitted.

Thank you,
Rodrigo

**Comment by oanguenot** [comment]
Delivered in v5.0.3
